import { prisma } from '@/lib/db'
import { detailJournalVoucher,listJournalVouchers,unwrapDetail,unwrapList } from '@/lib/accurate/journals'
import { openDatabase } from '@/lib/accurate/oauth'
import { NextResponse } from 'next/server'
import { appUrl } from '@/lib/app-url'
import { getCurrentUser } from '@/lib/auth'
import { mapAccountType } from '@/lib/accurate/accounts'
function dateFromAccurate(v:any){if(!v)return new Date();if(/^\d{2}\/\d{2}\/\d{4}/.test(v)){const[d,m,y]=v.slice(0,10).split('/').map(Number);return new Date(y,m-1,d)}return new Date(v)}
function detailLines(d:any){return d?.detailJournalVoucher||d?.detailJournalVouchers||d?.details||d?.detail||[]}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.redirect(appUrl('/login',req),303);const{id}=await params;const f=await req.formData(),from=String(f.get('from')||''),to=String(f.get('to')||'');let c=await prisma.company.findFirstOrThrow({where:{id,userId:user.id}});if(!c.accurateDbId)throw new Error('Database Accurate belum dipilih');const opened=await openDatabase(user.id,c.accurateDbId);c=await prisma.company.update({where:{id},data:{accurateHost:opened.host,sessionId:opened.sessionId}});let page=1,total=0;while(page<=200){const body=await listJournalVouchers({userId:user.id,host:c.accurateHost!,sessionId:c.sessionId,from:from||undefined,to:to||undefined,page,pageSize:100});const rows=unwrapList(body);if(!rows.length)break;for(const item of rows){const aid=String(item.id??item.number);let detail:any=item;try{detail=unwrapDetail(await detailJournalVoucher({userId:user.id,host:c.accurateHost!,sessionId:c.sessionId,id:aid}))}catch{}const j=await prisma.journal.upsert({where:{companyId_accurateId:{companyId:id,accurateId:aid}},update:{number:item.number?String(item.number):null,transDate:dateFromAccurate(item.transDate||detail.transDate),description:item.description||detail.description||null,raw:detail},create:{companyId:id,accurateId:aid,number:item.number?String(item.number):null,transDate:dateFromAccurate(item.transDate||detail.transDate),description:item.description||detail.description||null,raw:detail}});await prisma.journalLine.deleteMany({where:{journalId:j.id}});for(const l of detailLines(detail)){const accountNo=String(l.accountNo||l.account?.no||'UNKNOWN'),name=String(l.accountName||l.account?.name||accountNo);const a=await prisma.account.upsert({where:{companyId_accountNo:{companyId:id,accountNo}},update:{name,type:mapAccountType(l.accountType||l.account?.accountType)},create:{companyId:id,accountNo,name,type:mapAccountType(l.accountType||l.account?.accountType)}});const amount=Number(l.amount||0),t=String(l.amountType||'').toUpperCase(),debit=t==='DEBIT'?amount:Number(l.debit||0),credit=t==='CREDIT'?amount:Number(l.credit||0);await prisma.journalLine.create({data:{journalId:j.id,accountId:a.id,accountNo,memo:l.memo||null,debit,credit,customerNo:l.customerNo||null,vendorNo:l.vendorNo||null,projectNo:l.projectNo||null,department:l.departmentName||null}})}total++}if(rows.length<100)break;page++}return NextResponse.redirect(appUrl(`/companies?synced=${total}`,req),303)}
